// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version + '-qa',
  app_name: 'GetAPet',
  app_base_url: 'https://qa.getapet.dev',
  api_base_url: 'https://api.qa.getapet.dev/v1',
  fe_base_url: 'https://api.qa.getapet.dev/_fe',
  login_url: 'https://accounts.qa.getapet.dev/oauth/authorize',
  logout_url: 'https://accounts.qa.getapet.dev/oauth/logout',
  log_level: 0,
  enable_sentry: true,
  sentry_dsn: '',
  default_language: 'en-US',
  supported_languages: ['en-US', 'de-DE'],
  theme_color: '#142467',
};
